### ISSUE TITLE
Both-way dependency.

### ISSUE THREAD

**Issue by kaedea** [andrewhayden/archive-patcher#10]
It seems that `share` module depends on `sharetest` as well as `sharetest` depends on `share`.

**Comment by andrewhayden** [comment]
@kaedea, is this causing you some kind of build problem? If so, please provide details. AFAICT, this is correct:

- :shared has a _testCompile_ dependency on :sharedtest.
- :sharedtest has a normal _compile_ dependency on :shared.

@juliantoledo for the definitive answer, but I think this is fine.

**Comment by kaedea** [comment]
@andrewhayden, with the latest version of IntelliJ IDEA, it seems to make some error when I try to build an artifact from `:generator`. While it works when I downgrade to IDEA 2016.01. 

Maybe the task flows of building an artifact or something else is changing. I make `: sharedtest` depend on the output jar of `:shared` myself with the latest IDEA to deal with this issue.

**Comment by andrewhayden** [comment]
@juliantoledo, any chance you could fix up the build files?

**Comment by juliantoledo** [comment]
@kaedea I tried to reproduce the issue with IntelliJ IDEA 2017.2.2, and It works they way it is.

Any suggestion on what needs to be changed?

**Comment by kaedea** [comment]
@juliantoledo Nothing, everything **works well** in my project now. Thanks for this repository and sorry to disturb.
