### ISSUE TITLE
Truth incompatible with android

### ISSUE THREAD

**Issue by PokeMMO** [andrewhayden/archive-patcher#125]
Google truth imports unsafe and other unavailable apis on android.

Only test projects (And a single annotation in generator) rely on google truth.

Can be fixed by updating dependencies a little as in: https://github.com/PokeMMO/archive-patcher/commit/41b276af877ff4870cfaa6d54afb83f0e6af6260

**Comment by pspencil** [comment]
Looks sensible to me. One question though,

I though the "findbugs" dependency is for @VisibleForTesting. why did you
remove the annotation?

**Comment by PokeMMO** [comment]
@VisibleForTesting is in guava, or android's support-annotations.

findbugs is for javax.annotation.Nullable annotations (And maybe some more)

**Comment by pspencil** [comment]
https://github.com/google/archive-patcher/commit/ed1f764d454e391901bfa4d773d3503e3ebccd0b should have fixed this.
