### ISSUE TITLE
How to run the sample code?

### ISSUE THREAD

**Issue by fzyzcjy** [andrewhayden/archive-patcher#163]
Hi I am not very familiar with java compilation. Thus I wonder how should I run the code in `sample` dir? If I directly compile it, java complains that many classes are not defined. I also tried things like `javac -cp archive-patcher-1.0.jar ./SamplePatchGenerator.java && java SamplePatchGenerator` (with jar downloaded and put in the right location), but still no luck. Thanks!

**Comment by fzyzcjy** [comment]
OK I get it:

```
 javac -cp archive-patcher-1.0.jar:. ./SamplePatchGenerator.java && java -cp archive-patcher-1.0.jar:. SamplePatchGenerator
```

**Comment by andrewhayden** [comment]
That's one way to do it, certainly, and quite reasonable. The sample code is just here to show you how to write a patch generator and a patch applier. More fully:
* If you execute "gradle build" in the "generator" directory you will build the library necessary for a patch generator into generator/build/libs/generator.jar
* If you execute "gradle build" in the "applier" directory you will build the library necessary for a patch applier into applier/build/libs/applier.jar
* If you execute "gradle build" in the "common" directory you will built the library needed for both generator and applier (shared code)

To compile and/or run the sample patch generator you would need the "common" and "generator" libraries in your classpath. To compile and/or run the sample patch applier you would need the "common" and "applier" libraries in your classpath. There's no need to deploy the "applier" code on a system that only generates patches (e.g., a server), and no need to deploy the "generator" code on a system that only applies patches (e.g., a client).

**Comment by fzyzcjy** [comment]
Thank you very much for the detailed answer!

**Comment by andrewhayden** [comment]
Sure. Please see also https://github.com/google/archive-patcher/issues/16.
