### ISSUE TITLE
How to build code on branch v2

### ISSUE THREAD

**Issue by soheilrt** [andrewhayden/archive-patcher#171]
Hi, 
I'm not very familiar with java and when I want to build the code on branch v2, I get the following error:

```shell
soheil@soheil-thinkpad:~/projects/github/archive-patcher$ gradle build

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/soheil/projects/github/archive-patcher/applier/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating project ':applier'.
> Could not find method annotationProcessor() for arguments [com.google.auto.value:auto-value:1.6.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

```

Could anyone help me with how can I fix this error?

ps: I can build source code from the master branch but since there are lots of files that I need to create a patch for them daily, I really need a huge improvement on the algorithm's performance. I would really thankful if you would give me some tips on how to improve the algorithm's speed.

Thanks in advance.

**Comment by suntong30** [comment]
> Hi, I'm not very familiar with java and when I want to build the code on branch v2, I get the following error:
> 
> ```shell
> soheil@soheil-thinkpad:~/projects/github/archive-patcher$ gradle build
> 
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/soheil/projects/github/archive-patcher/applier/build.gradle' line: 9
> 
> * What went wrong:
> A problem occurred evaluating project ':applier'.
> > Could not find method annotationProcessor() for arguments [com.google.auto.value:auto-value:1.6.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> ```
> 
> Could anyone help me with how can I fix this error?
> 
> ps: I can build source code from the master branch but since there are lots of files that I need to create a patch for them daily, I really need a huge improvement on the algorithm's performance. I would really thankful if you would give me some tips on how to improve the algorithm's speed.
> 
> Thanks in advance.

Hi @soheilrt , I occurred same error problems while building branch v2. Have you addressed this error? Any suggestions?
Thanks in advance.
